"""
Django settings for DjangoServer project.

Generated by 'django-admin startproject' using Django 3.2.
"""

import os
from pathlib import Path

from django.contrib.messages import constants as messages
from django.core.management.utils import get_random_secret_key


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent
SETTINGS_PATH = BASE_DIR


# ---------------------------------------------------------------------------
# Security
# ---------------------------------------------------------------------------

# Never hard-code production secrets in source code.
#
# Set DJANGO_SECRET_KEY in your environment:
#
# DJANGO_SECRET_KEY=your-secret-key
#
# The fallback allows local development to start if the variable is missing.
# For production, it is strongly recommended that the environment variable
# always be configured.
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

if not SECRET_KEY:
    if os.getenv("DJANGO_ENV", "development").lower() == "production":
        raise RuntimeError(
            "DJANGO_SECRET_KEY must be configured in production."
        )

    SECRET_KEY = get_random_secret_key()


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() in ("true", "1", "yes")


# ---------------------------------------------------------------------------
# Allowed hosts
# ---------------------------------------------------------------------------

# Configure this through an environment variable.
#
# Example:
# DJANGO_ALLOWED_HOSTS=timesheets-django.herokuapp.com,localhost,127.0.0.1
#
ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "DJANGO_ALLOWED_HOSTS",
        "localhost,127.0.0.1",
    ).split(",")
    if host.strip()
]


# ---------------------------------------------------------------------------
# CSRF trusted origins
# ---------------------------------------------------------------------------

# Required when Django is receiving POST requests from HTTPS origins that
# differ from the host.
#
# Example:
# DJANGO_CSRF_TRUSTED_ORIGINS=https://timesheets-django.herokuapp.com
#
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]


# ---------------------------------------------------------------------------
# Security headers / HTTPS
# ---------------------------------------------------------------------------

if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"

    # These are appropriate when your production deployment is HTTPS.
    SECURE_SSL_REDIRECT = os.getenv(
        "SECURE_SSL_REDIRECT",
        "False",
    ).lower() in ("true", "1", "yes")

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Heroku and other reverse proxies commonly terminate HTTPS before
    # forwarding the request to Django.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# ---------------------------------------------------------------------------
# Application definition
# ---------------------------------------------------------------------------

INSTALLED_APPS = [
    "timesheets.apps.TimesheetsConfig",
    "sefas_admin.apps.SefasAdminConfig",

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "crispy_forms",
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "DjangoServer.urls"


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "DjangoServer.wsgi.application"


# ---------------------------------------------------------------------------
# Messages
# ---------------------------------------------------------------------------

MESSAGE_TAGS = {
    messages.ERROR: "danger",
}


# ---------------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------------

# MongoDB credentials MUST be supplied through environment variables.
#
# Example:
#
# MONGO_HOST=mongodb+srv://cluster0.xxxxx.mongodb.net/timesheets
# MONGO_USERNAME=sefas_admin
# MONGO_PASSWORD=your-new-password
#
# Do NOT commit these values to Git.

MONGO_HOST = os.getenv("MONGO_HOST")
MONGO_USERNAME = os.getenv("MONGO_USERNAME")
MONGO_PASSWORD = os.getenv("MONGO_PASSWORD")


if not all([MONGO_HOST, MONGO_USERNAME, MONGO_PASSWORD]):
    if os.getenv("DJANGO_ENV", "development").lower() == "production":
        raise RuntimeError(
            "MONGO_HOST, MONGO_USERNAME and MONGO_PASSWORD "
            "must be configured in production."
        )


DATABASES = {
    "default": {
        "ENGINE": "djongo",
        "CLIENT": {
            "host": MONGO_HOST,
            "username": MONGO_USERNAME,
            "password": MONGO_PASSWORD,
            "authMechanism": os.getenv(
                "MONGO_AUTH_MECHANISM",
                "SCRAM-SHA-1",
            ),
        },
    }
}


# ---------------------------------------------------------------------------
# Password validation
# ---------------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# ---------------------------------------------------------------------------
# Internationalization
# ---------------------------------------------------------------------------

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True
USE_L10N = True
USE_TZ = True


# ---------------------------------------------------------------------------
# Static files
# ---------------------------------------------------------------------------

STATIC_URL = "/static/"

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

STATICFILES_STORAGE = (
    "whitenoise.storage.CompressedManifestStaticFilesStorage"
)


# ---------------------------------------------------------------------------
# Default primary key field type
# ---------------------------------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ---------------------------------------------------------------------------
# Crispy Forms
# ---------------------------------------------------------------------------

CRISPY_TEMPLATE_PACK = "bootstrap4"


# ---------------------------------------------------------------------------
# Authentication
# ---------------------------------------------------------------------------

LOGIN_REDIRECT_URL = "index"
LOGIN_URL = "login"


# ---------------------------------------------------------------------------
# Application-specific settings
# ---------------------------------------------------------------------------

DATE_INPUT_FORMATS = [
    "%d-%m-%Y",
]

DEFAULT_HOL_AMOUNT = 150

DEFAULT_TEAM = "PS"


# ---------------------------------------------------------------------------
# Email
# ---------------------------------------------------------------------------

EMAIL_FROM = os.getenv(
    "EMAIL_FROM",
    "timesheets@sefas.com",
)

EMAIL_HOST = os.getenv(
    "EMAIL_HOST",
    "172.28.81.43",
)


# ---------------------------------------------------------------------------
# Heroku
# ---------------------------------------------------------------------------

# django-heroku automatically configures a number of Django settings based
# on the Heroku environment.
#
# Keep this at the bottom of the file.

try:
    import django_heroku

    django_heroku.settings(
        locals(),
        staticfiles=False,
    )

except ImportError:
    # django-heroku is not installed in every environment.
    pass