# Generated by Django 3.0.5 on 2021-05-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sefas_admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
