# Generated by Django 3.2.13 on 2022-07-21 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sefas_admin', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=30)),
                ('manager', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
