# Generated by Django 3.2 on 2022-07-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sefas_admin', '0003_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=30)),
            ],
        ),
    ]
