# Generated by Django 3.2.15 on 2022-10-31 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sefas_admin', '0008_auto_20220927_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('full_name',)},
        ),
        migrations.AlterModelOptions(
            name='jobcode',
            options={'ordering': ('code',)},
        ),
    ]
