# Generated by Django 3.0.5 on 2021-05-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0007_holiday_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
