# Generated by Django 3.0.5 on 2021-05-05 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0008_auto_20210505_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holiday',
            old_name='id',
            new_name='holidayid',
        ),
    ]
