# Generated by Django 3.0.5 on 2021-05-05 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0009_auto_20210505_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='user',
        ),
    ]
