# Generated by Django 3.0.5 on 2021-05-05 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0010_remove_holiday_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Holiday',
        ),
    ]
