# Generated by Django 3.0.5 on 2021-05-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0012_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='note',
            field=models.CharField(default='', max_length=50),
        ),
    ]
