# Generated by Django 3.0.5 on 2021-05-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0013_holiday_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='hours',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='note',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
