# Generated by Django 3.0.5 on 2021-05-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0014_auto_20210505_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
