# Generated by Django 3.2.13 on 2022-07-21 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sefas_admin', '0003_team'),
        ('timesheets', '0016_auto_20210506_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankHoliday',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='holiday',
            name='include_weekends',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='holiday_awaiting_approval',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
        # migrations.AlterField(
        #     model_name='holiday',
        #     name='approved',
        #     field=models.CharField(choices=[('0', 'PENDING'), ('1', 'APPROVED'), ('2', 'REJECTED')], default='0', max_length=1),
        # ),
        # migrations.AlterField(
        #     model_name='holiday',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.AlterField(
        #     model_name='profile',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.AlterField(
        #     model_name='profile',
        #     name='team',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sefas_admin.team'),
        # ),
    ]
