# Generated by Django 3.2.13 on 2022-07-21 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sefas_admin', '0003_team'),
        ('timesheets', '0017_auto_20220721_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sefas_admin.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('customer', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('note', models.CharField(max_length=500)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheets.day')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='timesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheets.timesheet'),
        ),
    ]
