# Generated by Django 3.2.13 on 2022-07-21 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0018_auto_20220721_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('customer', models.CharField(max_length=20)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheets.day')),
            ],
        ),
    ]
