# Generated by Django 3.2 on 2022-07-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0021_auto_20220725_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='total_hours',
            field=models.FloatField(),
        ),
    ]
