# Generated by Django 3.2 on 2022-08-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0026_auto_20220803_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='total_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
