# Generated by Django 3.2 on 2022-08-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0029_alter_day_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
