# Generated by Django 3.2 on 2022-08-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0033_auto_20220819_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(),
        ),
    ]
