# Generated by Django 3.2 on 2022-09-01 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0039_auto_20220831_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MaxValueValidator(7.5), django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
