# Generated by Django 3.2.15 on 2022-10-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0046_auto_20221010_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_title',
            new_name='project',
        ),
        migrations.AlterField(
            model_name='holiday',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='holiday_allowance',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='holiday_awaiting_approval',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='holiday_remaining',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
