# Generated by Django 3.2.15 on 2022-10-31 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0048_rename_project_job_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_hours',
        ),
    ]
