# Generated by Django 3.2.15 on 2022-11-21 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0052_auto_20221121_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankholiday',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheets.day'),
        ),
    ]
