# Generated by Django 3.2.15 on 2022-11-21 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0053_alter_bankholiday_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankholiday',
            old_name='date',
            new_name='day',
        ),
    ]
