# Generated by Django 3.2.15 on 2022-11-22 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0055_auto_20221122_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankholiday',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankholiday',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheets.day', unique=True),
        ),
    ]
