# Generated by Django 3.2.15 on 2022-11-22 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0056_auto_20221122_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankHoliday',
        ),
    ]
