# Generated by Django 3.2.15 on 2022-11-24 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0058_bankholiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankholiday',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheets.day'),
        ),
    ]
